# Generated by Django 4.2.6 on 2023-12-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank_data',
            name='Id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
