# Generated by Django 4.2.6 on 2023-12-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tanks_height_alter_tanks_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanks',
            name='life_time',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tanks',
            name='status',
            field=models.TextField(default='Static'),
        ),
    ]
