# Generated by Django 4.2.6 on 2023-12-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tanks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanks',
            name='valve_no',
            field=models.SmallIntegerField(default=0),
        ),
    ]
