# Generated by Django 4.2.6 on 2023-12-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tanks_valve_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanks',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
