# Generated by Django 4.2.6 on 2023-12-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_tanks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank_data',
            name='pump_mode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
