# Generated by Django 4.2.6 on 2023-12-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tank_data_pump_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank_data',
            name='Time',
        ),
        migrations.AlterField(
            model_name='tank_data',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
