# Generated by Django 4.2.6 on 2024-01-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_date_tank_data_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanks',
            name='Container_id',
        ),
    ]
